# Generated by Django 3.2.7 on 2021-11-23 17:05

import apps.audios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='archivo',
            field=models.FileField(storage=apps.audios.models.OverWriteStorage(), upload_to=apps.audios.models.ruta_archivo),
        ),
    ]
