# Generated by Django 3.2.7 on 2021-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_alter_audio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
