# Generated by Django 3.2.7 on 2021-11-22 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieTiempoAmplitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('pickle', models.FileField(upload_to='')),
                ('tasa_muestreo', models.PositiveIntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MffcEspectrogramaMel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('pickle', models.FileField(upload_to='')),
                ('tasa_muestreo', models.PositiveIntegerField()),
                ('n_fft', models.PositiveIntegerField()),
                ('hop_length', models.PositiveIntegerField()),
                ('n_mfcc', models.PositiveIntegerField()),
                ('dct_type', models.PositiveIntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MffcAmplitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('pickle', models.FileField(upload_to='')),
                ('tasa_muestreo', models.PositiveIntegerField()),
                ('n_mfcc', models.PositiveIntegerField()),
                ('dct_type', models.PositiveIntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EspectrogramaTradicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('pickle', models.FileField(upload_to='')),
                ('tasa_muestreo', models.PositiveIntegerField()),
                ('n_fft', models.PositiveIntegerField()),
                ('hop_length', models.PositiveIntegerField()),
                ('y_axis', models.CharField(max_length=10)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EspectrogramaMel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('pickle', models.FileField(upload_to='')),
                ('tasa_muestreo', models.PositiveIntegerField()),
                ('n_fft', models.PositiveIntegerField()),
                ('hop_length', models.PositiveIntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
