# Generated by Django 3.2.7 on 2021-11-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caracteristicas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espectrogramatradicional',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='espectrogramatradicional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mffcamplitud',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='mffcamplitud',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='mffcespectrogramamel',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='mffcespectrogramamel',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='serietiempoamplitud',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='serietiempoamplitud',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='EspectrogramaMel',
        ),
        migrations.DeleteModel(
            name='EspectrogramaTradicional',
        ),
        migrations.DeleteModel(
            name='MffcAmplitud',
        ),
        migrations.DeleteModel(
            name='MffcEspectrogramaMel',
        ),
        migrations.DeleteModel(
            name='SerieTiempoAmplitud',
        ),
    ]
